[tools]
age = "latest"
go = "1.26.4"
"go:filippo.io/mkcert" = "v1.4.4"
"go:github.com/air-verse/air" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "v3.27.1"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
sqlite = "latest"

[env]
DATABASE_URL = "./db/dev.db"
SSH_SERVER_KEY_FILE = "./priv/id_ed25519"
GOOSE_MIGRATION_DIR = "db/migrations"
GOOSE_DBSTRING = "{{ env.DATABASE_URL }}"
GOOSE_DRIVER = "sqlite3"
TLS_CERT_FILE = "./priv/cert.pem"
TLS_KEY_FILE = "./priv/key.pem"
BASE_DOMAIN = "pindakaas.localhost"
TZ = "UTC"
SECRET_KEY_BASE = "3V0DSIZp5596foaWQqsSCw6xkK3Q44SRBBsBTq2+zu6+tkIjLu2MrdqVwKKxRQLRVfvECiuBg07Yc8eS8hLRPQ=="
GOOGLE_CLIENT_ID = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVjA1ZzNYeWFiK29VeE9Hb0NJN2M5cXpWbm81M0FoRnp1NkZyRlFOLzJBCnlvbHAzQWhnSnpXcUJweXdQdmk2N2tuZm56cHF5QmhqbllibEcycDIzYncKLT4gc3NoLWVkMjU1MTkgc0dxOUN3IHFmVUhnWUFyZWQxR0tuNlhLSWRyUjhqTlJITDVMU3MxTzA4eUlPTnJRVW8KbWE2UmZIdnVweDNwV0lxOFJsMWxhY0k3dmM2ZHpwcEp6SUVhaXJKM0xVVQotPiBzc2gtcnNhIHNmK21WdwpEZUdtSlpPbEZJZUFVaDdUbElWUVJGL25jNG5BL0gvL0ZMV3pkVnRGcElMNlNjTjBNMzA0dk1qaUhNWHAxYzJNCkFraTFVZzBZMi9JSnFkdExBVTlTcnp2NmI3Q1ZuSTU0M2k4WVE2TTRDUGhLQkdqTjZGQmc0dWhPWFROWHR6TzgKU0ljZzFCTDdRay9VdGFvU0Z3cEYzNWppREhaYzBqeG9UODFSQ0I1V1ZmWmI3ckVUU29wMllyMmp1VXM0WHJ0OQpBS2tOdkcxNGd4KzFkdEhTWTdkUDM3ZnpnRGtsQUYyK3JaYmJ5azUwNi9Td0xySjZXV0RGTGVEZ1NJOEJlZm8rClk5cVlPWVNPM2NXd0JYZ0xKQ1FQZGxidWdrcTlDMVJwZ0xtTTdMV0hmZnNRcUJad1RZbGdMU2h4SGl3TW9CTjAKYWVybVZETnNGczMxRXB6SXhxd2VhQQotPiBeRDdxOkpXTi1ncmVhc2UgQSAiIEUnbSAmRCdXClBiYVp6SkczcVBsRGMyQ3RXa0FXWGhQNktTNGNCMnlxaFJjQlY2Skl3ekVac2U3ZXQyOEJZQkFpdXJDNjFkUlkKZnRwMVdQTHA4R2YxM3cKLS0tIEdoOEswQk9ITjBDalduMWEyaWFtNE9zd0tEVTJmd2NhYlZPTTBOOEgxYk0KU34s3BB5djRVaE1wEnlLg1l57sLs/wJ+hq6UluCPzS5fzFy0K03Sy9561dQ/EIQwfIYr8rf4ZhfECCBUGR/+ge/7yselupAvKKJZuQhwJhlJCyBnlyU4ki05WHJWyLmtAPX7QDF2LNE" }
GOOGLE_CLIENT_SECRET = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM2xYcDJhYU5SUUt6VE9FWEFpcG9qaDI1STZsRFFmVThkNkpQQUVWR3pVCnlSOGRoRTVNRGtESlVmSmhhWDRiaUdFVkpRZFA1dW1YWDIyR291VjRQNGcKLT4gc3NoLWVkMjU1MTkgc0dxOUN3IDhObWZzVm1aZklMQmpEMG5ZcTZ5SVVYcFJYS1hmZzhjSWs3QmZOTGZOU28KQ3pRNDhLREFBcXNXSm9RaTRCSDhBeFBKa2E5NHpUQnNvOTRHYUlpVkdmcwotPiBzc2gtcnNhIHNmK21WdwpPUXhXMmk4b1pFZldJY2ozVy80amJMV3NRZzBwWmkyN2UzL05FRTR2WkdEdHVLeVJhQk52UDg4ZklLZ2lOSXRjClBsYnF6b05FbWpJbXNOek1qOUZnUGU4WUczZTJGc2JEYXJYVUNyb0tVd3Rxbno3eWxSTmttdnVIYzB4N2R5YUcKUW4rZFV5ME5DSWtreEdVaWR0cjhoZXBPSkswL1c5Z1ZTQXovRmRscWpmSFFsV1NnUXRFMmRVYVVqKzZWOFU5VApBWUplM095akh2eWVycTN4ZUM0dGNjTmpJOExFNFpZTzdMWHovdlYrSnNhblFEWkQrTGc0WDd4MlJDWFJqUkp6Cm5YYUF2NVUrVHVCS0tmOGtIWi9uRlhUWEhJNFJ2ajhONjExQmloMlNpTDZpcnd5MytjR3UrdWZGaXNJYWc0SHEKZEdlRC9aREFRWHhISGEveFUwMU8vQQotPiB3cjRdUlA5Xy1ncmVhc2UgN3JhXlgKSENpa1lJL2tUd3M5RDZQZDRVSlBhd1JkYnMwNXRpRkUKLS0tIGZhSGxkY3NTOFVFU2RhTE1PeTJOL2NlM0lRRXhBVTM4MGxvR1lOOXNBY3cKR0iYYyqIOTt5FXZTJtcGYJVRISo8Nk1cQbp6N7PL9gBGl0mSQXoZ5gJvQ0P5cDjrXFfLGiK7jdsE2wkP72Mv2NICTQ" }

[tasks.setup]
depends = ["keygen", "db:setup"]

[tasks."db:reset"]
run = """
rm -rf {{ env.DATABASE_URL }}
mise db:setup
"""

[tasks."db:setup"]
run = """
goose up
mise db:seed
"""

[tasks."db:seed"]
run = "sqlite3 $DATABASE_URL < db/seeds.sql"

[tasks."keygen.ssh"]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ ! -f "$SSH_SERVER_KEY_FILE" ]]; then
  ssh-keygen -t ed25519 -f $SSH_SERVER_KEY_FILE -N ""
else
  echo "$SSH_SERVER_KEY_FILE exists, skipping..."
fi
"""

[tasks."keygen.tls"]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ -f "$TLS_KEY_FILE" ]] && [[ -f "$TLS_CERT_FILE" ]]; then
  echo "TLS key and certificate file exist, skipping..."
  exit 0
fi

mkcert -key-file "$TLS_KEY_FILE" -cert-file "$TLS_CERT_FILE" "$BASE_DOMAIN" "*.$BASE_DOMAIN"
"""
