[tools]
go = "1.26.4"
"go:github.com/air-verse/air" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "v3.27.1"

[tasks."server:keygen"]
run = """
#!/usr/bin/env -S bash -euo pipefail

if [[ ! -f "$SERVER_KEY" ]]; then
  ssh-keygen -t ed25519 -f $SERVER_KEY -N ""
else
  echo "$SERVER_KEY exists, skipping..."
fi
"""

[env]
SERVER_KEY = "./priv/id_ed25519"
GOOSE_MIGRATION_DIR = "db/migrations"
GOOSE_DBSTRING = "./dev.db"
GOOSE_DRIVER = "sqlite3"

[tasks.deploy]
dir = "{{ config_root }}/deploy"
run = "ansible-playbook -v deploy.yml"
