// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package queries

import (
	"context"
)

const getHostByUsername = `-- name: GetHostByUsername :one
select id, subdomain, username, password_hash, inserted_at, updated_at from hosts where username = ?
`

func (q *Queries) GetHostByUsername(ctx context.Context, username string) (*Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByUsername, username)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordHash,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listHosts = `-- name: ListHosts :many
select id, subdomain, username, password_hash, inserted_at, updated_at from hosts order by id
`

func (q *Queries) ListHosts(ctx context.Context) ([]*Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Subdomain,
			&i.Username,
			&i.PasswordHash,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
