// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	uuid "github.com/google/uuid"
	"github.com/moroz/pindakaas/types/dbtypes"
)

type Tunnel struct {
	ID           uuid.UUID
	Subdomain    string
	Username     string
	PasswordHash string
	InsertedAt   dbtypes.UnixTimestamp
	UpdatedAt    dbtypes.UnixTimestamp
	UserID       uuid.UUID
}

type User struct {
	ID         uuid.UUID
	Email      string
	UserRole   interface{}
	InsertedAt dbtypes.UnixTimestamp
	UpdatedAt  dbtypes.UnixTimestamp
}

type UserToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Token      []byte
	Context    dbtypes.UserTokenContext
	InsertedAt dbtypes.UnixTimestamp
}
