// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	uuid "github.com/google/uuid"
	"github.com/moroz/pindakaas/types/dbtypes"
)

type Tunnel struct {
	ID                uuid.UUID                 `json:"id"`
	Subdomain         string                    `json:"subdomain"`
	Username          string                    `json:"username"`
	PasswordEncrypted sqlcrypter.EncryptedBytes `json:"passwordEncrypted"`
	InsertedAt        dbtypes.UnixTimestamp     `json:"insertedAt"`
	UpdatedAt         dbtypes.UnixTimestamp     `json:"updatedAt"`
	UserID            uuid.UUID                 `json:"userId"`
}

type User struct {
	ID         uuid.UUID             `json:"id"`
	Email      string                `json:"email"`
	UserRole   interface{}           `json:"userRole"`
	GivenName  *string               `json:"givenName"`
	FamilyName *string               `json:"familyName"`
	Avatar     *string               `json:"avatar"`
	InsertedAt dbtypes.UnixTimestamp `json:"insertedAt"`
	UpdatedAt  dbtypes.UnixTimestamp `json:"updatedAt"`
}

type UserToken struct {
	ID         uuid.UUID                `json:"id"`
	UserID     uuid.UUID                `json:"userId"`
	Token      []byte                   `json:"token"`
	Context    dbtypes.UserTokenContext `json:"context"`
	InsertedAt dbtypes.UnixTimestamp    `json:"insertedAt"`
}
