// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tunnels.sql

package queries

import (
	"context"

	uuid "github.com/google/uuid"
)

const getTunnelByUsername = `-- name: GetTunnelByUsername :one
select id, subdomain, username, password_hash, inserted_at, updated_at, user_id from tunnels where username = ?
`

func (q *Queries) GetTunnelByUsername(ctx context.Context, username string) (*Tunnel, error) {
	row := q.db.QueryRowContext(ctx, getTunnelByUsername, username)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordHash,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const insertTunnel = `-- name: InsertTunnel :one
insert into tunnels (id, subdomain, username, password_hash, user_id)
values (?, ?, ?, ?, ?)
returning id, subdomain, username, password_hash, inserted_at, updated_at, user_id
`

type InsertTunnelParams struct {
	ID           uuid.UUID
	Subdomain    string
	Username     string
	PasswordHash string
	UserID       uuid.UUID
}

func (q *Queries) InsertTunnel(ctx context.Context, arg *InsertTunnelParams) (*Tunnel, error) {
	row := q.db.QueryRowContext(ctx, insertTunnel,
		arg.ID,
		arg.Subdomain,
		arg.Username,
		arg.PasswordHash,
		arg.UserID,
	)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordHash,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const listTunnels = `-- name: ListTunnels :many
select id, subdomain, username, password_hash, inserted_at, updated_at, user_id from tunnels order by id
`

func (q *Queries) ListTunnels(ctx context.Context) ([]*Tunnel, error) {
	rows, err := q.db.QueryContext(ctx, listTunnels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Tunnel
	for rows.Next() {
		var i Tunnel
		if err := rows.Scan(
			&i.ID,
			&i.Subdomain,
			&i.Username,
			&i.PasswordHash,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTunnelsForUser = `-- name: ListTunnelsForUser :many
select id, subdomain, username, password_hash, inserted_at, updated_at, user_id from tunnels where user_id = ? order by id
`

func (q *Queries) ListTunnelsForUser(ctx context.Context, userID uuid.UUID) ([]*Tunnel, error) {
	rows, err := q.db.QueryContext(ctx, listTunnelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Tunnel
	for rows.Next() {
		var i Tunnel
		if err := rows.Scan(
			&i.ID,
			&i.Subdomain,
			&i.Username,
			&i.PasswordHash,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
