// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tunnels.sql

package queries

import (
	"context"

	sqlcrypter "github.com/bincyber/go-sqlcrypter"
	uuid "github.com/google/uuid"
)

const deleteTunnelForUser = `-- name: DeleteTunnelForUser :exec
delete from tunnels where id = ? and user_id = ?
`

type DeleteTunnelForUserParams struct {
	TunnelID uuid.UUID `json:"tunnelId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteTunnelForUser(ctx context.Context, arg *DeleteTunnelForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteTunnelForUser, arg.TunnelID, arg.UserID)
	return err
}

const getTunnelByUsername = `-- name: GetTunnelByUsername :one
select id, subdomain, username, password_encrypted, inserted_at, updated_at, user_id from tunnels where username = ?
`

func (q *Queries) GetTunnelByUsername(ctx context.Context, username string) (*Tunnel, error) {
	row := q.db.QueryRowContext(ctx, getTunnelByUsername, username)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordEncrypted,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const getTunnelForUser = `-- name: GetTunnelForUser :one
select id, subdomain, username, password_encrypted, inserted_at, updated_at, user_id from tunnels where id = ? and user_id = ?
`

type GetTunnelForUserParams struct {
	TunnelID uuid.UUID `json:"tunnelId"`
	UserID   uuid.UUID `json:"userId"`
}

func (q *Queries) GetTunnelForUser(ctx context.Context, arg *GetTunnelForUserParams) (*Tunnel, error) {
	row := q.db.QueryRowContext(ctx, getTunnelForUser, arg.TunnelID, arg.UserID)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordEncrypted,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const insertTunnel = `-- name: InsertTunnel :one
insert into tunnels (id, subdomain, username, password_encrypted, user_id)
values (?, ?, ?, ?, ?)
returning id, subdomain, username, password_encrypted, inserted_at, updated_at, user_id
`

type InsertTunnelParams struct {
	ID                uuid.UUID                 `json:"id"`
	Subdomain         string                    `json:"subdomain"`
	Username          string                    `json:"username"`
	PasswordEncrypted sqlcrypter.EncryptedBytes `json:"passwordEncrypted"`
	UserID            uuid.UUID                 `json:"userId"`
}

func (q *Queries) InsertTunnel(ctx context.Context, arg *InsertTunnelParams) (*Tunnel, error) {
	row := q.db.QueryRowContext(ctx, insertTunnel,
		arg.ID,
		arg.Subdomain,
		arg.Username,
		arg.PasswordEncrypted,
		arg.UserID,
	)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.Subdomain,
		&i.Username,
		&i.PasswordEncrypted,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const listTunnelsForUser = `-- name: ListTunnelsForUser :many
select id, subdomain, username, password_encrypted, inserted_at, updated_at, user_id from tunnels where user_id = ? order by id desc
`

func (q *Queries) ListTunnelsForUser(ctx context.Context, userID uuid.UUID) ([]*Tunnel, error) {
	rows, err := q.db.QueryContext(ctx, listTunnelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Tunnel
	for rows.Next() {
		var i Tunnel
		if err := rows.Scan(
			&i.ID,
			&i.Subdomain,
			&i.Username,
			&i.PasswordEncrypted,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
