// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/moroz/pindakaas/types/dbtypes"
)

const findUserByUserToken = `-- name: FindUserByUserToken :one
select u.id, u.email, u.user_role, u.given_name, u.family_name, u.avatar, u.inserted_at, u.updated_at from users u
join user_tokens ut on u.id = ut.user_id
where ut.inserted_at + cast(?1 as bigint) > unixepoch()
and ut.token = ?2 and ut.context = ?3
`

type FindUserByUserTokenParams struct {
	Validity int64                    `json:"validity"`
	Token    []byte                   `json:"token"`
	Context  dbtypes.UserTokenContext `json:"context"`
}

func (q *Queries) FindUserByUserToken(ctx context.Context, arg *FindUserByUserTokenParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUserToken, arg.Validity, arg.Token, arg.Context)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.GivenName,
		&i.FamilyName,
		&i.Avatar,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, user_role, given_name, family_name, avatar, inserted_at, updated_at from users where email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.GivenName,
		&i.FamilyName,
		&i.Avatar,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, email, given_name, family_name, avatar)
values (?, ?, ?, ?, ?) returning id, email, user_role, given_name, family_name, avatar, inserted_at, updated_at
`

type InsertUserParams struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	GivenName  *string   `json:"givenName"`
	FamilyName *string   `json:"familyName"`
	Avatar     *string   `json:"avatar"`
}

func (q *Queries) InsertUser(ctx context.Context, arg *InsertUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.GivenName,
		&i.FamilyName,
		&i.Avatar,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertUserToken = `-- name: InsertUserToken :one
insert into user_tokens (id, user_id, token, context)
values (?, ?, ?, ?) returning id, user_id, token, context, inserted_at
`

type InsertUserTokenParams struct {
	ID      uuid.UUID                `json:"id"`
	UserID  uuid.UUID                `json:"userId"`
	Token   []byte                   `json:"token"`
	Context dbtypes.UserTokenContext `json:"context"`
}

func (q *Queries) InsertUserToken(ctx context.Context, arg *InsertUserTokenParams) (*UserToken, error) {
	row := q.db.QueryRowContext(ctx, insertUserToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Context,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Context,
		&i.InsertedAt,
	)
	return &i, err
}

const revokeUserToken = `-- name: RevokeUserToken :exec
delete from user_tokens where token = ?
`

func (q *Queries) RevokeUserToken(ctx context.Context, token []byte) error {
	_, err := q.db.ExecContext(ctx, revokeUserToken, token)
	return err
}

const upsertUser = `-- name: UpsertUser :one
insert into users (id, email, given_name, family_name, avatar)
values (?, ?, ?, ?, ?)
on conflict (email)
do update set
  given_name = excluded.given_name,
  family_name = excluded.family_name,
  avatar = excluded.avatar,
  updated_at = (unixepoch())
returning id, email, user_role, given_name, family_name, avatar, inserted_at, updated_at
`

type UpsertUserParams struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	GivenName  *string   `json:"givenName"`
	FamilyName *string   `json:"familyName"`
	Avatar     *string   `json:"avatar"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg *UpsertUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.GivenName,
		&i.FamilyName,
		&i.Avatar,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
