// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/moroz/pindakaas/types/dbtypes"
)

const findUserByUserToken = `-- name: FindUserByUserToken :one
select u.id, u.email, u.user_role, u.inserted_at, u.updated_at from users u
join user_tokens ut on u.id = ut.user_id
where ut.inserted_at + cast(?1 as bigint) > unixepoch()
and ut.token = ?2 and ut.context = ?3
`

type FindUserByUserTokenParams struct {
	Validity int64
	Token    []byte
	Context  dbtypes.UserTokenContext
}

func (q *Queries) FindUserByUserToken(ctx context.Context, arg *FindUserByUserTokenParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUserToken, arg.Validity, arg.Token, arg.Context)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertUserToken = `-- name: InsertUserToken :one
insert into user_tokens (id, user_id, token, context)
values (?, ?, ?, ?) returning id, user_id, token, context, inserted_at
`

type InsertUserTokenParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Token   []byte
	Context dbtypes.UserTokenContext
}

func (q *Queries) InsertUserToken(ctx context.Context, arg *InsertUserTokenParams) (*UserToken, error) {
	row := q.db.QueryRowContext(ctx, insertUserToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Context,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Context,
		&i.InsertedAt,
	)
	return &i, err
}
